# Prometheus 설정 파일
global:
  scrape_interval: 15s          # 메트릭 수집 간격
  evaluation_interval: 15s      # 규칙 평가 간격
  external_labels:
    monitor: 'pposeek-monitor'

# 알람 규칙 파일 위치
rule_files:
  - "rules/*.yml"

# 메트릭 수집 대상 설정
scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot 애플리케이션 메트릭
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['spring-backend:8080']
    scrape_timeout: 4s

  # Node Exporter (시스템 메트릭)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (컨테이너 메트릭)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Kafka JMX 메트릭 (선택사항)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: '/metrics'
    scrape_interval: 30s

# 알람 매니저 설정 (선택사항)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093