name: Build and Deploy to ACA

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push Docker image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/my-app:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

    - name: Update ACA container image
      run: |
        az containerapp update \
          --name ${{ secrets.ACA_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ env.IMAGE_NAME }}
